import {HttpsError} from "firebase-functions/v2/https";
import {
  COL,
  FieldValue,
  db,
} from "../core";
import {
  getLicensePlanPolicy,
  classifyActivationSlot,
  type LicensePlan,
  type LicensePlatform,
} from "./license-policy";

export type LicenseStatus = "active" | "suspended" | "revoked";

export interface LicenseRecord {
  ownerUid: string;
  ownerEmail?: string | null;
  plan: LicensePlan;
  primaryPlatform: LicensePlatform;
  status: LicenseStatus;
  source: string;
  orderId?: string | null;
  stripeCustomerId?: string | null;
  baseDeviceLimit: number;
  bonusOtherPlatformLimit: number;
  activeBaseDevices: number;
  activeBonusDevices: number;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface DeviceActivationRequest {
  installationId: string;
  platform: LicensePlatform;
  deviceName?: string | null;
  appVersion?: string | null;
}

export interface DeviceActivationResult {
  licenseId: string;
  installationId: string;
  slotType: "base" | "bonus";
  alreadyActive: boolean;
  activeBaseDevices: number;
  activeBonusDevices: number;
  baseDeviceLimit: number;
  bonusOtherPlatformLimit: number;
}

function normalizeInstallationId(value: string): string {
  const id = value.trim();
  if (!id || id.length > 200) {
    throw new HttpsError("invalid-argument", "Invalid installation id.");
  }
  return id;
}

function deviceDocId(licenseId: string, installationId: string): string {
  // Installation ids are generated by the app. Encoding keeps Firestore ids
  // safe even if a future client uses punctuation not valid for direct paths.
  return `${licenseId}__${Buffer.from(installationId, "utf8").toString("base64url")}`;
}

export function licenseIdForOwner(ownerUid: string): string {
  return `4icad__${ownerUid}`;
}

export async function createOrUpdateLicense(params: {
  ownerUid: string;
  ownerEmail?: string | null;
  plan: LicensePlan;
  primaryPlatform: LicensePlatform;
  source: string;
  orderId?: string | null;
  stripeCustomerId?: string | null;
}): Promise<string> {
  const policy = getLicensePlanPolicy(params.plan);
  const licenseId = licenseIdForOwner(params.ownerUid);
  const ref = db.collection(COL.licenses).doc(licenseId);

  await db.runTransaction(async (tx) => {
    const existing = await tx.get(ref);
    const current = existing.data() as Partial<LicenseRecord> | undefined;

    tx.set(
      ref,
      {
        ownerUid: params.ownerUid,
        ownerEmail: params.ownerEmail ?? current?.ownerEmail ?? null,
        plan: params.plan,
        primaryPlatform: params.primaryPlatform,
        status: current?.status ?? "active",
        source: params.source,
        orderId: params.orderId ?? current?.orderId ?? null,
        stripeCustomerId:
          params.stripeCustomerId ?? current?.stripeCustomerId ?? null,
        baseDeviceLimit: policy.baseDeviceLimit,
        bonusOtherPlatformLimit: policy.bonusOtherPlatformLimit,
        // Never reset counters on an idempotent webhook retry or plan metadata
        // refresh. Device mutations are the only place these counters change.
        activeBaseDevices: current?.activeBaseDevices ?? 0,
        activeBonusDevices: current?.activeBonusDevices ?? 0,
        createdAt: current?.createdAt ?? FieldValue.serverTimestamp(),
        updatedAt: FieldValue.serverTimestamp(),
      },
      {merge: true}
    );
  });

  return licenseId;
}

export async function getOwnerLicense(ownerUid: string): Promise<{
  id: string;
  data: LicenseRecord;
} | null> {
  const id = licenseIdForOwner(ownerUid);
  const snap = await db.collection(COL.licenses).doc(id).get();
  if (!snap.exists) return null;
  return {id, data: snap.data() as LicenseRecord};
}

export async function activateDevice(
  ownerUid: string,
  request: DeviceActivationRequest
): Promise<DeviceActivationResult> {
  const licenseId = licenseIdForOwner(ownerUid);
  const installationId = normalizeInstallationId(request.installationId);
  const licenseRef = db.collection(COL.licenses).doc(licenseId);
  const deviceRef = db
    .collection(COL.licenseDevices)
    .doc(deviceDocId(licenseId, installationId));

  return db.runTransaction(async (tx) => {
    const [licenseSnap, deviceSnap] = await Promise.all([
      tx.get(licenseRef),
      tx.get(deviceRef),
    ]);

    if (!licenseSnap.exists) {
      throw new HttpsError("permission-denied", "No active 4iCAD license was found.");
    }

    const license = licenseSnap.data() as LicenseRecord;
    if (license.ownerUid !== ownerUid || license.status !== "active") {
      throw new HttpsError("permission-denied", "This 4iCAD license is not active.");
    }

    const existing = deviceSnap.data() as
      | {active?: boolean; slotType?: "base" | "bonus"; platform?: LicensePlatform}
      | undefined;

    if (deviceSnap.exists && existing?.active === true) {
      const slotType = existing.slotType ??
        classifyActivationSlot(license.primaryPlatform, existing.platform ?? request.platform);
      tx.set(
        deviceRef,
        {
          lastSeenAt: FieldValue.serverTimestamp(),
          deviceName: request.deviceName ?? null,
          appVersion: request.appVersion ?? null,
        },
        {merge: true}
      );
      return {
        licenseId,
        installationId,
        slotType,
        alreadyActive: true,
        activeBaseDevices: license.activeBaseDevices ?? 0,
        activeBonusDevices: license.activeBonusDevices ?? 0,
        baseDeviceLimit: license.baseDeviceLimit,
        bonusOtherPlatformLimit: license.bonusOtherPlatformLimit,
      };
    }

    const slotType = classifyActivationSlot(
      license.primaryPlatform,
      request.platform
    );
    const activeBaseDevices = license.activeBaseDevices ?? 0;
    const activeBonusDevices = license.activeBonusDevices ?? 0;

    if (slotType === "base" && activeBaseDevices >= license.baseDeviceLimit) {
      throw new HttpsError(
        "resource-exhausted",
        `Primary-platform device limit reached (${license.baseDeviceLimit}).`
      );
    }
    if (
      slotType === "bonus" &&
      activeBonusDevices >= license.bonusOtherPlatformLimit
    ) {
      throw new HttpsError(
        "resource-exhausted",
        `Other-platform bonus device limit reached (${license.bonusOtherPlatformLimit}).`
      );
    }

    const nextBase = activeBaseDevices + (slotType === "base" ? 1 : 0);
    const nextBonus = activeBonusDevices + (slotType === "bonus" ? 1 : 0);

    tx.set(
      deviceRef,
      {
        licenseId,
        ownerUid,
        installationId,
        platform: request.platform,
        slotType,
        deviceName: request.deviceName ?? null,
        appVersion: request.appVersion ?? null,
        active: true,
        activatedAt: FieldValue.serverTimestamp(),
        lastSeenAt: FieldValue.serverTimestamp(),
        deactivatedAt: null,
      },
      {merge: true}
    );
    tx.update(licenseRef, {
      activeBaseDevices: nextBase,
      activeBonusDevices: nextBonus,
      updatedAt: FieldValue.serverTimestamp(),
    });

    const auditRef = db.collection(COL.licenseAudit).doc();
    tx.set(auditRef, {
      action: "device_activated",
      licenseId,
      ownerUid,
      installationId,
      platform: request.platform,
      slotType,
      createdAt: FieldValue.serverTimestamp(),
    });

    return {
      licenseId,
      installationId,
      slotType,
      alreadyActive: false,
      activeBaseDevices: nextBase,
      activeBonusDevices: nextBonus,
      baseDeviceLimit: license.baseDeviceLimit,
      bonusOtherPlatformLimit: license.bonusOtherPlatformLimit,
    };
  });
}

export async function deactivateDevice(
  ownerUid: string,
  installationIdValue: string
): Promise<{deactivated: boolean}> {
  const licenseId = licenseIdForOwner(ownerUid);
  const installationId = normalizeInstallationId(installationIdValue);
  const licenseRef = db.collection(COL.licenses).doc(licenseId);
  const deviceRef = db
    .collection(COL.licenseDevices)
    .doc(deviceDocId(licenseId, installationId));

  return db.runTransaction(async (tx) => {
    const [licenseSnap, deviceSnap] = await Promise.all([
      tx.get(licenseRef),
      tx.get(deviceRef),
    ]);
    if (!licenseSnap.exists || !deviceSnap.exists) return {deactivated: false};

    const license = licenseSnap.data() as LicenseRecord;
    const device = deviceSnap.data() as {
      ownerUid?: string;
      active?: boolean;
      slotType?: "base" | "bonus";
      platform?: LicensePlatform;
    };
    if (license.ownerUid !== ownerUid || device.ownerUid !== ownerUid) {
      throw new HttpsError("permission-denied", "Device does not belong to this license.");
    }
    if (device.active !== true) return {deactivated: false};

    const slotType = device.slotType ??
      classifyActivationSlot(
        license.primaryPlatform,
        device.platform ?? license.primaryPlatform
      );
    const nextBase = Math.max(
      0,
      (license.activeBaseDevices ?? 0) - (slotType === "base" ? 1 : 0)
    );
    const nextBonus = Math.max(
      0,
      (license.activeBonusDevices ?? 0) - (slotType === "bonus" ? 1 : 0)
    );

    tx.update(deviceRef, {
      active: false,
      deactivatedAt: FieldValue.serverTimestamp(),
      lastSeenAt: FieldValue.serverTimestamp(),
    });
    tx.update(licenseRef, {
      activeBaseDevices: nextBase,
      activeBonusDevices: nextBonus,
      updatedAt: FieldValue.serverTimestamp(),
    });

    const auditRef = db.collection(COL.licenseAudit).doc();
    tx.set(auditRef, {
      action: "device_deactivated",
      licenseId,
      ownerUid,
      installationId,
      slotType,
      createdAt: FieldValue.serverTimestamp(),
    });

    return {deactivated: true};
  });
}
