import {HttpsError} from "firebase-functions/v2/https";
import {COL, FieldValue, db} from "../core";
import {
  decideNewActivation,
  getLicensePlanPolicy,
  type ActivationBucket,
  type DevicePlatform,
  type LicensePlan,
} from "./license-policy";

export type LicenseStatus = "active" | "suspended" | "revoked";

export interface LicenseRecord {
  ownerUid: string;
  ownerEmail?: string | null;
  plan: LicensePlan;
  primaryPlatform: DevicePlatform;
  status: LicenseStatus;
  source: string;
  orderId?: string | null;
  stripeCustomerId?: string | null;
  primaryDeviceLimit: number;
  bonusOtherPlatformLimit: number;
  totalDeviceLimit: number;
  activePrimaryDevices: number;
  activeBonusDevices: number;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface DeviceActivationRequest {
  installationId: string;
  platform: DevicePlatform;
  deviceName?: string | null;
  appVersion?: string | null;
}

export interface DeviceActivationResult {
  licenseId: string;
  installationId: string;
  bucket: ActivationBucket;
  alreadyActive: boolean;
  activePrimaryDevices: number;
  activeBonusDevices: number;
  primaryDeviceLimit: number;
  bonusOtherPlatformLimit: number;
  totalDeviceLimit: number;
}

export interface LicenseDeviceRecord {
  licenseId: string;
  ownerUid: string;
  installationId: string;
  platform: DevicePlatform;
  bucket: ActivationBucket;
  deviceName?: string | null;
  appVersion?: string | null;
  active: boolean;
  activatedAt?: unknown;
  lastSeenAt?: unknown;
  deactivatedAt?: unknown;
}

function normalizeInstallationId(value: string): string {
  const id = value.trim();
  if (!id || id.length > 200) {
    throw new HttpsError("invalid-argument", "Invalid installation id.");
  }
  return id;
}

function deviceDocId(licenseId: string, installationId: string): string {
  // Installation ids are generated by the app. Encoding keeps Firestore ids
  // safe even if a future client uses punctuation not valid for direct paths.
  return `${licenseId}__${Buffer.from(installationId, "utf8").toString("base64url")}`;
}

export function licenseIdForOwner(ownerUid: string): string {
  return `4icad__${ownerUid}`;
}

/**
 * Create or refresh a license without resetting activation counters.
 * This makes Stripe webhook retries and metadata refreshes idempotent.
 */
export async function createOrUpdateLicense(params: {
  ownerUid: string;
  ownerEmail?: string | null;
  plan: LicensePlan;
  primaryPlatform: DevicePlatform;
  source: string;
  orderId?: string | null;
  stripeCustomerId?: string | null;
}): Promise<string> {
  const policy = getLicensePlanPolicy(params.plan);
  const licenseId = licenseIdForOwner(params.ownerUid);
  const ref = db.collection(COL.licenses).doc(licenseId);

  await db.runTransaction(async (tx) => {
    const existing = await tx.get(ref);
    const current = existing.data() as Partial<LicenseRecord> | undefined;

    tx.set(
      ref,
      {
        ownerUid: params.ownerUid,
        ownerEmail: params.ownerEmail ?? current?.ownerEmail ?? null,
        plan: params.plan,
        primaryPlatform: params.primaryPlatform,
        status: current?.status ?? "active",
        source: params.source,
        orderId: params.orderId ?? current?.orderId ?? null,
        stripeCustomerId:
          params.stripeCustomerId ?? current?.stripeCustomerId ?? null,
        primaryDeviceLimit: policy.primaryDeviceLimit,
        bonusOtherPlatformLimit: policy.bonusOtherPlatformLimit,
        totalDeviceLimit: policy.totalDeviceLimit,
        activePrimaryDevices: current?.activePrimaryDevices ?? 0,
        activeBonusDevices: current?.activeBonusDevices ?? 0,
        createdAt: current?.createdAt ?? FieldValue.serverTimestamp(),
        updatedAt: FieldValue.serverTimestamp(),
      },
      {merge: true}
    );
  });

  return licenseId;
}

export async function getOwnerLicense(ownerUid: string): Promise<{
  id: string;
  data: LicenseRecord;
} | null> {
  const id = licenseIdForOwner(ownerUid);
  const snap = await db.collection(COL.licenses).doc(id).get();
  if (!snap.exists) return null;
  return {id, data: snap.data() as LicenseRecord};
}

export async function listOwnerDevices(ownerUid: string): Promise<LicenseDeviceRecord[]> {
  const licenseId = licenseIdForOwner(ownerUid);
  const snap = await db
    .collection(COL.licenseDevices)
    .where("licenseId", "==", licenseId)
    .get();
  return snap.docs.map((doc) => doc.data() as LicenseDeviceRecord);
}

export async function activateDevice(
  ownerUid: string,
  request: DeviceActivationRequest
): Promise<DeviceActivationResult> {
  const licenseId = licenseIdForOwner(ownerUid);
  const installationId = normalizeInstallationId(request.installationId);
  const licenseRef = db.collection(COL.licenses).doc(licenseId);
  const deviceRef = db
    .collection(COL.licenseDevices)
    .doc(deviceDocId(licenseId, installationId));

  return db.runTransaction(async (tx) => {
    const licenseSnap = await tx.get(licenseRef);
    const deviceSnap = await tx.get(deviceRef);

    if (!licenseSnap.exists) {
      throw new HttpsError("permission-denied", "No active 4iCAD license was found.");
    }

    const license = licenseSnap.data() as LicenseRecord;
    if (license.ownerUid !== ownerUid || license.status !== "active") {
      throw new HttpsError("permission-denied", "This 4iCAD license is not active.");
    }

    const existing = deviceSnap.data() as Partial<LicenseDeviceRecord> | undefined;
    if (deviceSnap.exists && existing?.active === true) {
      // Same installation is idempotent. Never let a caller change its platform
      // to move an already-consumed seat between buckets.
      const bucket = existing.bucket ??
        (existing.platform === license.primaryPlatform ? "primary" : "bonus");
      tx.set(
        deviceRef,
        {
          lastSeenAt: FieldValue.serverTimestamp(),
          deviceName: request.deviceName ?? existing.deviceName ?? null,
          appVersion: request.appVersion ?? existing.appVersion ?? null,
        },
        {merge: true}
      );
      return {
        licenseId,
        installationId,
        bucket,
        alreadyActive: true,
        activePrimaryDevices: license.activePrimaryDevices ?? 0,
        activeBonusDevices: license.activeBonusDevices ?? 0,
        primaryDeviceLimit: license.primaryDeviceLimit,
        bonusOtherPlatformLimit: license.bonusOtherPlatformLimit,
        totalDeviceLimit: license.totalDeviceLimit,
      };
    }

    const primaryActive = license.activePrimaryDevices ?? 0;
    const bonusActive = license.activeBonusDevices ?? 0;
    const decision = decideNewActivation(
      license.plan,
      license.primaryPlatform,
      request.platform,
      {primaryActive, bonusActive}
    );

    if (!decision.allowed) {
      const limit =
        decision.bucket === "primary"
          ? license.primaryDeviceLimit
          : license.bonusOtherPlatformLimit;
      const message =
        decision.bucket === "primary"
          ? `Primary-platform device limit reached (${limit}).`
          : `Other-platform bonus device limit reached (${limit}).`;
      throw new HttpsError("resource-exhausted", message);
    }

    const nextPrimary = primaryActive + (decision.bucket === "primary" ? 1 : 0);
    const nextBonus = bonusActive + (decision.bucket === "bonus" ? 1 : 0);

    tx.set(
      deviceRef,
      {
        licenseId,
        ownerUid,
        installationId,
        platform: request.platform,
        bucket: decision.bucket,
        deviceName: request.deviceName ?? null,
        appVersion: request.appVersion ?? null,
        active: true,
        activatedAt: FieldValue.serverTimestamp(),
        lastSeenAt: FieldValue.serverTimestamp(),
        deactivatedAt: null,
      },
      {merge: true}
    );
    tx.update(licenseRef, {
      activePrimaryDevices: nextPrimary,
      activeBonusDevices: nextBonus,
      updatedAt: FieldValue.serverTimestamp(),
    });

    const auditRef = db.collection(COL.licenseAudit).doc();
    tx.set(auditRef, {
      action: "device_activated",
      licenseId,
      ownerUid,
      installationId,
      platform: request.platform,
      bucket: decision.bucket,
      createdAt: FieldValue.serverTimestamp(),
    });

    return {
      licenseId,
      installationId,
      bucket: decision.bucket,
      alreadyActive: false,
      activePrimaryDevices: nextPrimary,
      activeBonusDevices: nextBonus,
      primaryDeviceLimit: license.primaryDeviceLimit,
      bonusOtherPlatformLimit: license.bonusOtherPlatformLimit,
      totalDeviceLimit: license.totalDeviceLimit,
    };
  });
}

export async function deactivateDevice(
  ownerUid: string,
  installationIdValue: string
): Promise<{deactivated: boolean}> {
  const licenseId = licenseIdForOwner(ownerUid);
  const installationId = normalizeInstallationId(installationIdValue);
  const licenseRef = db.collection(COL.licenses).doc(licenseId);
  const deviceRef = db
    .collection(COL.licenseDevices)
    .doc(deviceDocId(licenseId, installationId));

  return db.runTransaction(async (tx) => {
    const licenseSnap = await tx.get(licenseRef);
    const deviceSnap = await tx.get(deviceRef);
    if (!licenseSnap.exists || !deviceSnap.exists) return {deactivated: false};

    const license = licenseSnap.data() as LicenseRecord;
    const device = deviceSnap.data() as LicenseDeviceRecord;
    if (license.ownerUid !== ownerUid || device.ownerUid !== ownerUid) {
      throw new HttpsError("permission-denied", "Device does not belong to this license.");
    }
    if (device.active !== true) return {deactivated: false};

    const bucket: ActivationBucket =
      device.bucket ??
      (device.platform === license.primaryPlatform ? "primary" : "bonus");
    const nextPrimary = Math.max(
      0,
      (license.activePrimaryDevices ?? 0) - (bucket === "primary" ? 1 : 0)
    );
    const nextBonus = Math.max(
      0,
      (license.activeBonusDevices ?? 0) - (bucket === "bonus" ? 1 : 0)
    );

    tx.update(deviceRef, {
      active: false,
      deactivatedAt: FieldValue.serverTimestamp(),
      lastSeenAt: FieldValue.serverTimestamp(),
    });
    tx.update(licenseRef, {
      activePrimaryDevices: nextPrimary,
      activeBonusDevices: nextBonus,
      updatedAt: FieldValue.serverTimestamp(),
    });

    const auditRef = db.collection(COL.licenseAudit).doc();
    tx.set(auditRef, {
      action: "device_deactivated",
      licenseId,
      ownerUid,
      installationId,
      bucket,
      createdAt: FieldValue.serverTimestamp(),
    });

    return {deactivated: true};
  });
}
