// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq7FR8cT4ZKqnbpfpal7AcmaRWpu55b68',
    appId: '1:68544054220:web:3986ff51628f4c925d9369',
    messagingSenderId: '68544054220',
    projectId: 'my-web-page-ef286',
    authDomain: 'my-web-page-ef286.firebaseapp.com',
    storageBucket: 'my-web-page-ef286.firebasestorage.app',
    measurementId: 'G-G1WEKVH128',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbkcpk4Y7FF1JLCpc3rJnKT1iz3Fg8MI',
    appId: '1:68544054220:android:9ddee97ac1a357655d9369',
    messagingSenderId: '68544054220',
    projectId: 'my-web-page-ef286',
    storageBucket: 'my-web-page-ef286.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIYSW8Qukg_gwgwmnZiRVyqEBm3MG-2HE',
    appId: '1:68544054220:ios:a294c604e3b3cfbd5d9369',
    messagingSenderId: '68544054220',
    projectId: 'my-web-page-ef286',
    storageBucket: 'my-web-page-ef286.firebasestorage.app',
    iosClientId: '68544054220-hdkfbpv63iti3oq8cbo425eo5crf1vse.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWebSite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIYSW8Qukg_gwgwmnZiRVyqEBm3MG-2HE',
    appId: '1:68544054220:ios:a294c604e3b3cfbd5d9369',
    messagingSenderId: '68544054220',
    projectId: 'my-web-page-ef286',
    storageBucket: 'my-web-page-ef286.firebasestorage.app',
    iosClientId: '68544054220-hdkfbpv63iti3oq8cbo425eo5crf1vse.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWebSite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq7FR8cT4ZKqnbpfpal7AcmaRWpu55b68',
    appId: '1:68544054220:web:f8ec22ac1148c1cf5d9369',
    messagingSenderId: '68544054220',
    projectId: 'my-web-page-ef286',
    authDomain: 'my-web-page-ef286.firebaseapp.com',
    storageBucket: 'my-web-page-ef286.firebasestorage.app',
    measurementId: 'G-CP2149MKFK',
  );
}
